- src/include/lind_platform.h
> lind platform update

- src/include/lind_platform.h
- tests/test_cases/dup2.c
> update include for exec

- tests/test_cases/serverclient.c
> added server client test for netcalls

- src/mklind
This update functionality pulls changes for lind_project, nacl_repy, native_client, and lind_glibc for the develop branch. "download" has been moved to number 20 in `make` as number 2 was assigned to update.
> Added update functionality to make

- tests/applications/nginx/bootstrap_nacl
Simple change to Nginx bootstrap file.
> Nginx make script change

- tests/test_cases/stat.c
A simple fix to `stat.c` by changing `lstat` to `stat`.
> Fix stat.c

- tests/test_cases/fstat.c
- tests/test_cases/stat.c
Note: If the test is running in Lind, files would have to be copied to `lindfs` before passed in as command line arguments.
> Add fstat.c

- tests/test_cases/pread_pwrite.c
Fixed a bug in the test case: pread_pwrite.c
resolves #165
> Fixed test case: pread_pwrite.c

- .github/workflows/daily-builds.yml
- .github/workflows/daily.yml
- README.md
This should add daily builds and include it in the Readme.md
> Daily builds

- tests/applications/openssl/bootstrap_nacl
Fixes symbol linking errors in OpenSSL build
> openssl build-fix

- tests/test_cases/dettests.txt
- tests/test_cases/dnstest.c
- tests/test_cases/popen.c
This is going to fail CI until the other 2 fix branches in native client and rustposix are merged, we should rerun it at that point
> Added a dns test

- src/scripts/copy_all.sh
- src/scripts/load_postgres.sh
- tests/test_cases/fork_simple.py
- tests/test_cases/forkandopen.py
- tests/test_cases/pipeonestring.py
General fix for pipe/fork tests, and extended coverage of postgres/copyall scripts.
> Fixed tests and scripts

- .github/workflows/daily-builds.yml
- .github/workflows/lind-selfhost.yml
Previous PR had the line in the wrong file. This should fix it.
> Cicd draft pr fix

- tests/test_cases/nondet.txt
- tests/test_cases/socketselect.c
- tests/test_cases/socketselect.py
- tests/test_cases/suite.sh
Cross PR w/ Nick.
Added socketselect.c and .py test case.
Polished suite: Different tests are more noticeable. Failed tests appear in the end as a list to help debugging.
> Socketselect

- tests/pipescript/pipescriptvar
- tests/pipescript/pipescriptvar-native
- tests/pipescript/read_from_pipe-test.c
- tests/pipescript/write_1gb_var-test.c
Adds some tests I've been working with and configures them so Ahmet can add them to the bash test suite.
> Pipescript tests

- Makefile
- tests/test_cases/fork_simple.c
- tests/test_cases/socketselect.c
Fixes on Socketselect (timeout issues, reduced to 2 seconds), makefile (for coreutils suite) and fork_simple (waits added)
> Small test fixes

- tests/test_cases/coreutils_suite/coreutils_suite.sh
Solves https://github.com/Lind-Project/lind_project/issues/246
> Coreutils suite build checking

- src/mklind
- src/scripts/lind
Updates mklind and lind scripts to properly locate runnable-ld.so
> Nacldesc scripts

- .github/pull_request_template.md
Added a PR template consisting of a checklist mentioning what part the PR affects. So that it's easier to add descriptions and understand what the changes are doing.
> PR template merge to main

- src/scripts/python/load_python.sh
Fixes #301 
This should have been part of PR #304 but was probably missed. So we were getting the import error show below
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
return …
```
> Fix import libffi.so.5 bug

- tests/test_cases/forkandopen.py
Update the regex in `tests/test_cases/forkandopen.py` which is used by `tests/test_cases/forkandopen.c` for verifying the output of the test in lind and native.
- `lind_project/tests/test_cases/forkandopen.c`
> tests: update regex in forkandopen.py

- src/scripts/lamp/flask-app/myproject.py
- src/scripts/lamp/flask-app/run_lamp.sh
Update the flask app `myproject.py` and `run_lamp.sh` to make sure that the app is configured and launched correctly.
- Running `src/scripts/lamp/flask-app/run_lamp.sh`
> Flask app fix

- Makefile
- src/docker/lind-base/Dockerfile
- src/docker/lind-lamp/Dockerfile
Added a new Dockerfile, for creating a pre built lamp stack backed by lind image. 
* builds on the lind-full image
* compiles and loads lamp stack
* runs the nginx server on startup
* requires port 80 to be exposed during docker run.
Fixes # (issue)
- Test A - `lind_project/tests/test_cases/test_a.c`
- Test B - `lind_project/tests/test_cases/test_b.c`
> Added new Docker image for lind lamp stack
